# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sanket Hanamashetti
full_name: Sanket J. Hanamashetti
email: sanketjh@ucsc.edu
# email2: 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sanketjh.github.io" # the base hostname & protocol for your site
github_username:  sanketjh
# twitter_username: 
linkedin_username: sanket-j-hanamashetti-908976198/
google_analytics:
  id: "G-T0EKLHWMS4"
# stackoverflow:
include: ['_pages']
footer-links-active:
  stackoverflow: false

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
